# The URL the site will be built for
base_url = "https://maxbruges.com/"
compile_sass = false
build_search_index = true
minify_html = true

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
bottom_footnotes = true
smart_punctuation = true
lazy_async_image = false
external_links_target_blank = true

[slugify]
anchors = "on"
paths = "safe"

[extra]
# Put all your custom variables here
icon = "ğŸˆâ€â¬›"
default_title = 'MaxBruges.com'
default_description = 'More stuff from Max Bruges'
footer = "MB ğŸˆâ€â¬› 2024"

[search]
include_title = true
include_description = true
include_content = true
include_path = true
